In [1]:
import numpy as np

In [68]:
a = np.asarray([[0,0,0,0,0],
[0,0,0,0,0],
[0,0,1,0,0],[1,1,1,1,1]],dtype=float)

In [37]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [73]:
x = 

In [74]:
x

2

In [22]:
np.asarray(x)

array([[3, 3, 3, 3, 3],
       [0, 1, 2, 3, 4]])

In [69]:
def baseAI(state):
    if state is None: return -1
    R,C = state.shape
    r,c = [],[]
    r,c = np.nonzero(state)
    score = 0
    score = r
    if len(r):
        score = min(r) #Keep the blocks as low as possible
    else:
        score = r
    return score

In [70]:
baseAI(a)

2

In [282]:
def baseAINumpy(state):
    if state is None: return -1
    if np.isin(state,[0]).all(): return state.shape[0] #Max height
    return np.min(np.nonzero(state)[0])

In [307]:
board = np.asarray([
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0]
])

In [308]:
print(board)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [309]:
baseAI(board) == baseAINumpy(board)

array([], dtype=bool)

In [310]:
baseAI(board)

array([], dtype=int64)

In [311]:
baseAINumpy(board)

5

In [291]:
np.nonzero(board)[0]

array([1, 1, 2, 4])