In [190]:
import numpy as np
import sys
sys.path.append("..")
from modules import shape as shx
from modules import grid
from scipy import signal

In [128]:
def validPositions(shape, GRID): #No of children's
    # returns set of positions where the block can be fixed
    ROW, COL = GRID.shape
    #print(f"Shape: {GRID.shape}")
    a,b = np.nonzero(shape) # a -> row | b-> col indices.
    #returns positions that need to be 0.
    pos = np.array(list(zip(a,b))) #tuple of arrays --> array of tuples.
    valid = []
    for row in range(ROW-1,-1,-1):
        print("C1")
        for col in range(COL-1,-1,-1): #Traverse through the grid.
            if all([a+row < ROW for a,_ in pos]) and all([b+col < COL for _,b in pos]) and all([GRID[a + row][b + col] == 0 for a,b in pos]):

                baseBlocks = np.argwhere(shape > 1)
                #print(f"ROW:{row} COL:{col} baseBlocks:{baseBlocks}")
                check = True
                for a,_ in baseBlocks:
                    if a + row + 1 == ROW:
                        valid.append((row,col))
                        check = False
                        break

                if check:
                    if any([GRID[a + row + 1][b + col] == 1 for a,b in baseBlocks]):
                        valid.append((row,col))
    return valid

In [121]:
from collections import defaultdict
val = defaultdict(int)
for row,col in zip(x[0],x[1]):
    val[col] = row
valid = []
for col,row in val.items():
    valid.append((row,col))


In [182]:
def numpyValidMoves(shape, GRID):
    if GRID is None: return []
    pos = signal.convolve2d(in1 = (1-GRID), in2= shape[::-1, ::-1],mode="valid")
    pos = np.where(pos == np.sum(shape))
    val = defaultdict(int)
    for row,col in zip(pos[0],pos[1]):
        val[col] = row
    valid = []
    for col,row in val.items():
        valid.append((row,col))
    return valid
    
    

In [184]:
print(TETRIS)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 1]]


In [185]:
numpyValidMoves(shape = currShape, GRID = TETRIS)

[(1, 0), (1, 1), (1, 2)]

In [186]:
#signal.convolve2d(in1 = (1-TETRIS), in2= currShape[::-1, ::-1],mode="valid")

array([[4, 4, 4],
       [4, 4, 4]])

In [194]:
s = shx.Shape()
s.printGridStates(shape = currShape, GRID = TETRIS)